# -*- coding: utf-8 -*-
"""covid 19 data project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEOTtgH2PD0v3_SkcmJOEzxg6N_6ydlm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

d=pd.read_csv('/content/country_wise_latest.csv',encoding='latin1')
d

#How many countries are present in the dataset?
d['ï»¿Country/Region'].nunique()

#What are the total confirmed COVID-19 cases worldwide?
d['Confirmed'].sum()

#What is the total number of deaths and recoveries globally?
d['Deaths'].sum()
d['Recovered'].sum()

#Which columns represent daily changes in cases?
d.columns

#List all unique WHO regions in the dataset.
d['WHO Region'].unique()

#Country-Level Analysis
#Which country has the highest number of confirmed cases?
d.sort_values(by="Confirmed", ascending=False)[["ï»¿Country/Region", "Confirmed"]].head(1)

#Which country has reported the maximum number of deaths?
d.sort_values(by="Deaths", ascending=False)[["ï»¿Country/Region", "Deaths"]].head(1)

#Which country has the highest number of recovered cases?
d.sort_values(by="Recovered", ascending=False)[["ï»¿Country/Region", "Recovered"]].head(1)

#Which country currently has the highest active cases?
d.sort_values(by="Active", ascending=False)[["ï»¿Country/Region", "Active"]].head(1)

#Identify the top 10 countries with the highest confirmed cases.
d.sort_values(by="Confirmed", ascending=False)[["ï»¿Country/Region", "Confirmed"]].head(10)

#Identify the top 10 countries with the highest death counts.
d.sort_values(by="Deaths", ascending=False)[["ï»¿Country/Region", "Deaths"]].head(10)

#Which country has reported zero new cases?
d[d["New cases"] == 0][["ï»¿Country/Region", "New cases"]]

#Which countries reported zero deaths so far?
d[d["Deaths"] == 0][["ï»¿Country/Region", "Deaths"]]

#Daily Trend Analysis
#Which country reported the highest new cases today?
d.sort_values(by="New cases", ascending=False)[["ï»¿Country/Region", "New cases"]].head(1)

#Which country reported the highest new deaths today?
d.sort_values(by="New deaths", ascending=False)[["ï»¿Country/Region", "New deaths"]].head(1)

#Which country recorded the highest new recoveries?
d.sort_values(by="New recovered", ascending=False)[["ï»¿Country/Region", "New recovered"]].head(1)

#How many countries reported new cases greater than 500?
d[d["New cases"]>500][["ï»¿Country/Region", "New cases"]]

#Which countries reported no new recoveries?
d[d["New recovered"] == 0][["ï»¿Country/Region", "New recovered"]]

#Recovery & Fatality Rate Analysis
#Which country has the highest death rate per 100 cases?
d["Death Rate"] = d["Deaths"] / d["Confirmed"] * 100
d.sort_values(by="Death Rate", ascending=False)[["ï»¿Country/Region", "Death Rate"]].head(1)

#Which country has the highest recovery rate per 100 cases?
d["Recovered"] = d["Recovered"] / d["Confirmed"] * 100
d.sort_values(by="Recovered", ascending=False)[["ï»¿Country/Region", "Recovered"]].head(1)

#Which countries have a death rate greater than 5%?
d[d["Death Rate"] > 5][["ï»¿Country/Region", "Death Rate"]]

#Which countries have a recovery rate above 80%?
d[d["Recovered"] > 80][["ï»¿Country/Region", "Recovered"]]

#Identify countries where Deaths / 100 Recovered is unusually high.
d["Deaths / 100 Recovered"] = d["Deaths"] / d["Recovered"] * 100
d.sort_values(by="Deaths / 100 Recovered", ascending=False)[["ï»¿Country/Region", "Deaths / 100 Recovered"]].head(10)

#Weekly Growth Analysis
#Which country has the highest increase in cases in the last week?
d.sort_values(by="1 week change", ascending=False)[["ï»¿Country/Region", "1 week change"]].head(1)

#Which country has the highest 1-week percentage increase?
d.sort_values(by="1 week % increase", ascending=False)[["ï»¿Country/Region", "1 week % increase"]].head(1)

#Which countries experienced a negative or zero weekly change?
d[d["1 week change"] == 0][["ï»¿Country/Region", "1 week change"]]

#Compare current confirmed cases vs last week confirmed cases.
d[["ï»¿Country/Region", "Confirmed",'Confirmed last week']].head()

#Which country’s COVID situation worsened the most in the last week?
d.sort_values(by="1 week change", ascending=False)[["ï»¿Country/Region", "1 week change", "1 week % increase"]].head()

#WHO Region-Wise Analysis
#Which WHO region has the highest total confirmed cases?
d.groupby("WHO Region")["Confirmed"].sum().sort_values(ascending=False).head(1)

#Which WHO region has the highest total deaths?
d.groupby("WHO Region")["Deaths"].sum().sort_values(ascending=False).head(1)

#Which WHO region shows the best recovery rate?
d.groupby("WHO Region")["Recovered"].sum().sort_values(ascending=False).head(1)

#Compare active cases across all WHO regions.
d.groupby("WHO Region")["Active"].sum().sort_values(ascending=False)

#Which WHO region reported the highest new cases today?
d.groupby("WHO Region")["New cases"].sum().sort_values(ascending=False).head(1)

#What are the total confirmed COVID-19 cases worldwide?
w= d['Confirmed'].sum()
plt.title('Total confirmed COVID-19 cases worldwide')
ax=sns.barplot(x=['Worldwide Confirmed Cases'], y=[w], palette='viridis', hue=['Worldwide Confirmed Cases'], legend=False)
plt.ylabel('Confirmed Cases')
for i in ax.containers:
  plt.bar_label(i, fmt='%.0f')
plt.show()

#Country-Level Analysis
#Identify the top 10 countries with the highest confirmed cases.
plt.figure(figsize=(10,5))
g = d.sort_values(by="Confirmed", ascending=False)[["ï»¿Country/Region", "Confirmed"]].head(10)
ax = sns.barplot(x='ï»¿Country/Region',y='Confirmed',data=g,palette='plasma')
plt.title('Top 10 Countries with Highest Confirmed Cases')
plt.xticks(rotation=45)
for i in ax.containers:
    ax.bar_label(i)

#Daily Trend Analysis
#How many countries reported new cases greater than 500?
plt.figure(figsize=(65,15))
w = d[d["New cases"] > 500][["ï»¿Country/Region", "New cases"]]
plt.bar(w['ï»¿Country/Region'],w['New cases'],width=0.5,color='blue',label='New Cases > 500')
plt.title('Countries with New Cases > 500')
plt.xticks(rotation=90)
plt.ylabel('New Cases')
plt.legend()

#Recovery & Fatality Rate Analysis
#Which countries have a death rate greater than 5%?
plt.figure(figsize=(55,15))
w = d[d["Death Rate"] > 5][["ï»¿Country/Region", "Death Rate"]]
plt.plot( w['ï»¿Country/Region'],w['Death Rate'],marker='o',linestyle='-',color='red',label='Death Rate > 5%')
plt.title('Countries with Death Rate > 5%')
plt.xticks(rotation=90)
plt.ylabel('Death Rate')
plt.grid(ls='dotted')
plt.legend()

#Weekly Growth Analysis
#Compare current confirmed cases vs last week confirmed cases.
w = d[["ï»¿Country/Region", "Confirmed", "Confirmed last week"]].head()
x_index = range(len(w))
plt.step(x_index, w['Confirmed last week'], where='mid', marker='o', label='Last Week confirmed cases')
plt.step(x_index, w['Confirmed'], where='mid', marker='^', label='Current confirmed cases')
plt.xticks(x_index, w['ï»¿Country/Region'], rotation=45)
plt.title('Confirmed vs Last Week')
plt.ylabel('Cases')
plt.grid(ls='dotted')
plt.legend()

#WHO Region-Wise Analysis
#Compare active cases across all WHO regions.
plt.figure(figsize=(10,5))
w=d.groupby("WHO Region")["Active"].sum().sort_values(ascending=False).reset_index()
sns.scatterplot(x='WHO Region',y='Active',data=w,s=200,marker='^',hue='WHO Region')
plt.grid(ls='dotted',c='r')
plt.title('Active Cases Across All WHO Regions')
plt.show()

#Dashboard
plt.figure(figsize=(45, 15))
plt.subplot(2, 3, 1)
w = d['Confirmed'].sum()
ax = sns.barplot(x=['Worldwide Confirmed Cases'],y=[w],palette='viridis')
plt.title('Total Confirmed COVID-19 Cases Worldwide')
plt.ylabel('Confirmed Cases')
for i in ax.containers:
    ax.bar_label(i, fmt='%.0f')

plt.subplot(2, 3, 2)
g = d.sort_values(by="Confirmed", ascending=False)[["ï»¿Country/Region", "Confirmed"]].head(10)
ax = sns.barplot(x='ï»¿Country/Region',y='Confirmed',data=g,palette='plasma')
plt.title('Top 10 Countries with Highest Confirmed Cases')
plt.xticks(rotation=45)
for i in ax.containers:
    ax.bar_label(i)

plt.subplot(2, 3, 3)
w = d[d["New cases"] > 500][["ï»¿Country/Region", "New cases"]]
plt.bar(w['ï»¿Country/Region'],w['New cases'],width=0.5,color='blue',label='New Cases > 500')
plt.title('Countries with New Cases > 500')
plt.xticks(rotation=90)
plt.ylabel('New Cases')
plt.legend()

plt.subplot(2, 3, 4)
w = d[d["Death Rate"] > 5][["ï»¿Country/Region", "Death Rate"]]
plt.plot( w['ï»¿Country/Region'],w['Death Rate'],marker='o',linestyle='-',color='red',label='Death Rate > 5%')
plt.title('Countries with Death Rate > 5%')
plt.xticks(rotation=90)
plt.ylabel('Death Rate')
plt.grid(ls='dotted')
plt.legend()

plt.subplot(2, 3, 5)
w = d[["ï»¿Country/Region", "Confirmed", "Confirmed last week"]].head()
x_index = range(len(w))
plt.step(x_index, w['Confirmed last week'], where='mid', marker='o', label='Last Week confirmed cases')
plt.step(x_index, w['Confirmed'], where='mid', marker='^', label='Current confirmed cases')
plt.xticks(x_index, w['ï»¿Country/Region'], rotation=45)
plt.title('Confirmed vs Last Week')
plt.ylabel('Cases')
plt.grid(ls='dotted')
plt.legend()


plt.subplot(2, 3, 6)
w = d.groupby("WHO Region")["Active"].sum().sort_values(ascending=False).reset_index()
sns.scatterplot(x='WHO Region',y='Active',data=w,s=150,marker='^',hue='WHO Region')
plt.title('Active Cases Across WHO Regions')
plt.grid(ls='dotted',c='r')
plt.tight_layout()
plt.show()